### ISSUE TITLE
Installation Skips to Step 8

### ISSUE THREAD

**Issue by drkthunder02** [evekb/evedev-kb#103]
Had evedev-kb installed on a server a while ago.  Deleted it.  Tried to re-install it just now.  The killboard just immediately skips to step 8 and does not install any tables or files.  How do I get it to stop skipping to step 8?

**Comment by Salvoxia** [comment]
Hi,

EDK stores the installation progress in a cookie so that you basically could abandon the installation process mid-way and continue later.
So you should delete any cookies for the domain your installing EDK on.

Best Regards,
Salvoxia
