### ISSUE TITLE
cron/cron_clearup.php doesn't purge mail cache

### ISSUE THREAD

**Issue by MikeWinter** [evekb/evedev-kb#14]
The kill mail cache is defined to be "cache/mails" (line 15, [common/includes/constants.php](https://github.com/evekb/evedev-kb/blob/4.0/common/includes/constants.php)) but the call to remove the oldest files is passed "mail" (line 67, [cron/cron_clearup.php](https://github.com/evekb/evedev-kb/blob/4.0/cron/cron_clearup.php)).

The latter line should read:

``` php
echo "Removed ".CacheHandler::removeByAge("mails/", $maxOtherAge * 24)." files from mails/<br />\n";
```

**Comment by Salvoxia** [comment]
Fixed in https://github.com/evekb/evedev-kb/commit/7f18c6b789d1b74ebbf998b2ec9891b00e0a0bda
