### ISSUE TITLE
Major logic flaw in IdFeed class

### ISSUE THREAD

**Issue by Kreastr** [evekb/evedev-kb#23]
In https://github.com/evekb/evedev-kb/blob/4.0-dev/common/includes/class.idfeed.php#L790 the check for presence of only npc's in the kill mail returns always returns false after the first kill mail parsed that contains a player. This seems to happen because the private $npcOnly variable( https://github.com/evekb/evedev-kb/blob/4.0-dev/common/includes/class.idfeed.php#L58 ) is never reinitialized while it is presumed by the logic of check happening in function ProcessVictims to be reset. The solution to this and similiar potential problems is to move variable initialization into corresponding functions(i.e. ProcessKill which seems to be the entrance function in this case) or to recreate the class instance every time before calling $this->processKill($row); ( https://github.com/evekb/evedev-kb/blob/4.0-dev/common/includes/class.idfeed.php#L485 )

**Comment by Salvoxia** [comment]
Hi,

the private $npcOnly variable is reinitialized for every kill right before processing of involved parties:
https://github.com/evekb/evedev-kb/blob/4.0-dev/common/includes/class.idfeed.php#L556
It then gets set as described by you and evaluated in https://github.com/evekb/evedev-kb/blob/4.0-dev/common/includes/class.idfeed.php#L576 where it is compared against the flag which gets set by the class instantiating the IDFeed class.
Looks fine to me, did I miss something?

Regards,
Salvoxia

P.S.: You seem to have looked at the old branch 4.0, whereas current development happens in 4.0-dev (you propable didn't have chance to know that), but the reinitialization of $npcOnly also happens in that old version in the same spot: https://github.com/evekb/evedev-kb/blob/4.0/common/includes/class.idfeed.php#L530

**Comment by Kreastr** [comment]
Hi,

I guess it's me accidently deleting that line while I was trying to find the cause of another bug with the same sympthome and just fixed one while breaking another. Sorry for bothering you.

With Best Regards,
Kreastr

**Comment by Salvoxia** [comment]
No problem mate :)
But if there is another bug, I am interested in that one. So let me know if you find something.

**Comment by Kreastr** [comment]
This one 4e58a739fc61727aa13acce54aeb56fb2b09777b. Found these messages on forum later.
