### ISSUE TITLE
Copy/paste typo in cron_zkb.php

### ISSUE THREAD

**Issue by StinGer-ShoGuN** [evekb/evedev-kb#24]
I think the title says it all...
There's an error on line 23 of cron_zkb.php causing the cron job to die when trying to chdir.

`$KB_HOME = preg_replace('/[\/\\\\]cron[\/\\\\]cron_feed\.php$/', '', __FILE__);`

Should be:

`$KB_HOME = preg_replace('/[\/\\\\]cron[\/\\\\]cron_zkb\.php$/', '', __FILE__);`

That's all folks !

**Comment by StinGer-ShoGuN** [comment]
Just added a pull request to correct it: #25 .

**Comment by hglock** [comment]
Fixed with commit b69331f.
