### ISSUE TITLE
Comments not displayed on kill_detail pages

### ISSUE THREAD

**Issue by StinGer-ShoGuN** [evekb/evedev-kb#29]
Hello guys !

I've had a weird issue for a couple of weeks now with our killboard: comments were counted and the count displayed on the summary page but they were not displayed on the kill detail page. In addition, we could still post comment. So in the end, all was working as expected, but the comments not being displayed where they should.

I've now solved the issue. I filled a pull request if you want.

Here is one of the errors I had when having a look at it:
`Non-static method xajaxPluginManager::getInstance() should not be called statically, assuming $this from incompatible context in /path/to/killboard/common/xajax/xajax_core/xajax.inc.php on line 275
Non-static method xajaxLanguageManager::getInstance() should not be called statically, assuming $this from incompatible context in /path/to/killboard/common/xajax/xajax_core/xajax.inc.php on line 278`

Now that I edited the method declarations, I can see the comments again !

**Comment by hglock** [comment]
Fix included with 624f522e20cba54f12506e135b873899a431b118
Thanks!
