### ISSUE TITLE
URL Fix for class.imageurl.php

### ISSUE THREAD

**Issue by 0mni** [evekb/evedev-kb#32]
In common/includes/class.imageurl.php at line 98

You have:

> if ($internal) {
> if(strpos($url, "?") !== false) {
> $url .= "&amp;int=1";
> } else {
> $url .= "?amp;int=1";
> }
> }
> return $url;

Should be:

> if ($internal) {
> if(strpos($url, "?") !== false) {
> $url .= "&amp;int=1";
> } else {
> $url .= "?int=1";
> }
> }
> return $url;

**Comment by Salvoxia** [comment]
THX, fixed!
