### ISSUE TITLE
Minor bug in class.ship.php

### ISSUE THREAD

**Issue by 0mni** [evekb/evedev-kb#33]
Bug with missing numbers in class.ship.php

Currently has

> ```
>            // replace showinfo links
>            $trait = preg_replace_callback('/showinfo:[1-9]+/', array($this, 'parseShowInfoLink'), $trait);
> ```

Should be

> ```
>            // replace showinfo links
>            $trait = preg_replace_callback('/showinfo:[0-9]+/', array($this, 'parseShowInfoLink'), $trait);
> ```

Otherwise a typeid that ends in 0, such as 3320 for the rocket skilll book, would show up as 332/0 when you have the "pretty" urls enabled.

**Comment by Salvoxia** [comment]
Thx, fixed!
