### ISSUE TITLE
[zKillboard] API modifications

### ISSUE THREAD

**Issue by karbowiak** [evekb/evedev-kb#34]
Hey there!

Just a heads up, the zKB source (not the one powering zkillboard.com) has had it's api changed.

to get kills you need to access /api/kills/
losses: /api/losses/
and both kills + losses: /api/combined/

more info here https://beta.eve-kill.net/api/list/
and https://beta.eve-kill.net/api/parameters/kills/ (and losses and combined)

**Comment by Salvoxia** [comment]
Hi,

thanks for the heads up! Do you know whether zKillboard.com will apply these changes as well any time soon? 

Regards,
Salvoxia

**Comment by karbowiak** [comment]
Absolutely no idea, but i think he will.

But you can tell the difference by checking if /api/list/ gives you anything in return except an error.
