### ISSUE TITLE
Since Carnyx Patch no Admin login possible

### ISSUE THREAD

**Issue by Dharr-Guartonzec** [evekb/evedev-kb#40]
Hi,

a day after i applied the last update for Carnyx, login in as admin no longer works. Also stats can not be opened anymore.

The Admin link http://serverurl.xyz/?a=admin ends up as http://serverurl.xyz/login/admin/ with the server reporting "The requested URL /login/admin/ was not found on this server." 

Something must be broken, but i not even see error log entries in apache.

Any idea?

-Dharr-

**Comment by Salvoxia** [comment]
Hi,

please see this commit for a fix:
https://github.com/evekb/evedev-kb/commit/81922330534591795bcc9a435ae718b7dbd03e50

We will release an hotfix update soon.

Regards,
Salvoxia

**Comment by Dharr-Guartonzec** [comment]
Hmm, ok. I changed the code in those files but seems i messed it up, now the KB noteven loads anymore. Error log still empty.

**Comment by Salvoxia** [comment]
Hi, I'm sorry to hear that.
Here you can find the hotfix bundled in a single zip file, you can simply upload the contents and overwrite existing files: http://www.evekb.org/downloads/edk_4.2.11.0_hotfix.zip

Regards,
Salvoxia
