### ISSUE TITLE
bug in class.corporations.php

### ISSUE THREAD

**Issue by jgoldshlag** [evekb/evedev-kb#44]
Line 253 reads:
"where crp_id = ".$this->id;

but that is in a static function. I think "$this->id" should be "$externalid", so you end up with:
"where crp_id = ".$externalid;

**Comment by Salvoxia** [comment]
Hi,

thanks for reporting.
Actually, it should be

``` php
where crp_id = ".$crp->getID();
```

since the crp_id column is the internal corp ID and we have a valid Corporation object at this point.

Regards,
Salvoxia
