### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by CokkocZateki** [evekb/evedev-kb#46]
error on installation

Database error: Duplicate column name 'kll_x'
SQL: ALTER TABLE kb3_kills ADD COLUMN `kll_x` double NOT NULL DEFAULT 0,ADD COLUMN `kll_y` double NOT NULL DEFAULT 0,ADD COLUMN `kll_z` double NOT NULL DEFAULT 0

Fatal error: SQL error (Duplicate column name 'kll_x' in /var/www/killboard/common/includes/class.dbnormalquery.php on line 46

**Comment by Salvoxia** [comment]
Hi,

that sounds like you are trying to apply an update that has already been applied.
Please execute the following statement on your killboard database:

``` sql
UPDATE kb3_config SET cfg_value = '038' WHERE cfg_key = 'DBUpdate';
```

Best Regards,
Salvoxia

**Comment by Salvoxia** [comment]
I also just pushed a patch for this problem.
