### ISSUE TITLE
memory_limit and cron_api.php

### ISSUE THREAD

**Issue by rolnick** [evekb/evedev-kb#48]
Why script cron_api.php need at least memory_limit = 812M in php,ini to run?

FreeBSD  10.1-RELEASE-p13 FreeBSD 10.1-RELEASE-p13
PHP 5.6.16 (cli) (built: Dec  1 2015 11:18:26) (DEBUG)
nginx version: nginx/1.8.0

Fatal error: Allowed memory size of 746586112 bytes exhausted at /usr/ports/lang/php56/work/php-5.6.16/ext/standard/var.c:595 (tried to allocate 6178 bytes) in /usr/local/www/kb/common/includes/class.cacheable.php on line 109

**Comment by Salvoxia** [comment]
Hi,

the amount of memory required by the cron job to import kills from the API strongly depends on the kind of data returned by the API. 
Given the right circumstances, a couple of hundred kills with a couple of hundred involved pilots per kill with a huge pile of loot in each kill might be returned (pretty much the worst case scenario). That data has to be parsed and processed, which might take a nice chunk of memory.

Best Regards,
Salvoxia
