### ISSUE TITLE
Killboard not updating

### ISSUE THREAD

**Issue by CokkocZateki** [evekb/evedev-kb#49]
Hi

For some reason the killboard wont update the latest kills. Ive added api keys etc but i have to manually update it daily myself

Any solution on this?

Thanks

**Comment by Salvoxia** [comment]
Hi,

have you set up the corresponding cron job? If not, please see the readme file in the cron folder for descriptions and recommended execution frequencies for each cron job.

Best Regards,
Salvoxia

**Comment by CokkocZateki** [comment]
ok i had a quick look at it but i dunno if the xmas punch is still punching me but i dont see that i can alter any numbers to change the cronjobs

**Comment by Salvoxia** [comment]
Okay, I don't quite understand what you mean.
Just to be clear: You have the cron jobs set up, just with other execution intervals? Are you using your webserver's crontab or are you working with the AJCron mod?

Best Regards,
Salvoxia

**Comment by CokkocZateki** [comment]
im using AJCron mod but its not updating

**Comment by Salvoxia** [comment]
Hi,

AJCron is a substitute for cron tab that relies on the killboard to be visited regularly. Each page visit triggers an internal check whether one of the configured jobs needs to be executed, and if so, it gets called asynchronously. 
If your killboard is not visited frequently enough, AJCron has no trigger.

Best Regards,
Salvoxia

**Comment by CokkocZateki** [comment]
Yeah i would need something more automated instead of AJCron. I noticed to add a api redirects to a non valid api mask. 

Where would i go in order to get the api key pulled for the kills. I looked in the cron job but it comes up all in one line

**Comment by CokkocZateki** [comment]
is there no way of getting it implemented into the build. make it a bit easier? still stuck on this case

**Comment by Salvoxia** [comment]
Hi,
automatic kill import depends on some mechanism that (periodically) calls the cron scripts. It is as easy as executing the PHP script. I don't really have an idea how to make it even more easy.

I admit using crontab on a command line level to set it up is a bit more complicated. Most hosting service provider would have some kind of web interface for setting up cronjobs. 
Are you running on an own (virtual) server or are you using an hosting service that could possibly help with that?

Best Regards,
Salvoxia

**Comment by CokkocZateki** [comment]
Hi Salvoxia.

yes it is def confusing at best. Okay i can check to see if there are any
on the web interface to setting it up.  Im running it from a host company
(vps)

**Comment by CokkocZateki** [comment]
im attempting to set it up myself thru ubuntu. 
- \* \* \* \* /usr/bin/php /var/www/killboard/cron/cron_api.php:

am i on the right track here or did i completly miss the boat?

**Comment by Salvoxia** [comment]
Hi,

you are on the right track! However, this would execute the cron every minute, so you might want to go with something like

```
0 */1 * * * /usr/bin/php /var/www/killboard/cron/cron_api.php
```

to execute it each hour (at minute 0).

Best Regards,
Salvoxia

**Comment by CokkocZateki** [comment]
i done it and the kb still doesnt update. now really clueless @Salvoxia

**Comment by Salvoxia** [comment]
Can you confirm the cron job was actually executed? You can redirect the cron job's output to a log file like this:

```
0 */1 * * * /usr/bin/php /var/www/killboard/cron/cron_api.php > /usr/log/edk_api.log
```

Make sure the PHP process has write rights at the log file destination. Then wait for the next full hour to pass.

**Comment by CokkocZateki** [comment]
that seems to work. however its not importing all kills. 

if i wanted to do zkillboard what would that entry be?

**Comment by Salvoxia** [comment]
Hi,
could you please post the contents of the log file that was generated? Hopefully we can figure out what's wrong.
If you want to fetch from zKillboard, pull up the entity you want to fetch kills for on zKillboard. Then look at the URL in your browser's address bar. It will look something like this:

```
https://zkillboard.com/corporation/1831131676/
```

To get the URL for the zKBFetch Configuration, add "ID" to "corporation" (or alliance, or character, whatever entity you are trying to fetch for), and put "api/" before "corporationID", so that it looks like this

```
https://zkillboard.com/api/corporationID/1831131676/
```

I hope that description was not too confusing ;)

Best Regards,
Salvoxia

**Comment by CokkocZateki** [comment]
sorry i wasnt to clear on my previous question. I meant to setup a cronjob to pull from zkill. was it similar as the previous but just add zkill iso cron.api.php

**Comment by Salvoxia** [comment]
Hi,

oh, yes. Setting up the cron for zKB Fetch works exactly like for the API, simply call cron_zkb.php instead of cron_api.php

Best Regards,
Salvoxia

**Comment by CokkocZateki** [comment]
sweet that done the trick :+1: thanks for all your help
