### ISSUE TITLE
deprecated mysql_connect

### ISSUE THREAD

**Issue by Flupster** [evekb/evedev-kb#50]
Update EDK to allow support for php7+ seeing as mysql_connect was deprecated in php5.5

Currently install fails on step 3 due to this deprecation

**Comment by Salvoxia** [comment]
Hi,

this branch contains fixes for this problem and is available for testing: https://github.com/evekb/evedev-kb/tree/php7
If all goes well these updates will be included in the February release.

Best Regards,
Salvoxia

**Comment by Flupster** [comment]
Of course i missed that, good work dude
