### ISSUE TITLE
Unable to pull from zkillboard

### ISSUE THREAD

**Issue by ghost** [evekb/evedev-kb#54]
I believe it broke 2 updates ago:

[Thu Mar 24 06:18:06.275969 2016] [:error] [pid 20047] [client 93.173.230.134:56769] PHP Fatal error:  Call to a member function getName() on boolean in /var/www/html/kb/common/includes/class.kill.php on line 1405, referer: https://example.com/kb/?a=admin_zkbfetch

**Comment by Salvoxia** [comment]
Thanks for reporting, this has been fixed with the commit above.

Best Regards,
Salvoxia

**Comment by ghost** [comment]
Great, it looks like this has fixed the problem.  My hotfix involved editing "class.kill.php" and checking if $item === false in, like, 10 different places, lol
