### ISSUE TITLE
Incorrect resistances?

### ISSUE THREAD

**Issue by ghost** [evekb/evedev-kb#57]
If you look at this picture, you'll see the armor resists are completely wrong.

![](http://i.imgur.com/d0ryG4D.png)

Link:  https://shadowcartel.com/kb/index.php/kill_detail/259059/

**Comment by Salvoxia** [comment]
Hi,

thanks for reporting!
Even though this problem affects the Ship Display Tool mod, I fixed it in the version I am maintaining.
Please see https://github.com/Salvoxia/ship_display_tool/tree/edk42160 for a fixed version.

Best Regards,
Salvoxia

**Comment by ghost** [comment]
Fixed thanks!
