### ISSUE TITLE
Several non-static method errors

### ISSUE THREAD

**Issue by sn0opy** [evekb/evedev-kb#61]
I moved the KB to another server which is running php7. Unfortunately since then, I'm getting the following errors while opening the kill detail page. Any workaround / fix for this?

`2016/06/08 19:46:17 [error] 13650#13650: *37416 FastCGI sent in stderr: "/public/mods/ship_display_tool/init.php on line 3002
PHP message: PHP 8192:  Non-static method fittingTools::returnShipSkills() should not be called statically in /public/mods/ship_display_tool/init.php on line 406
PHP message: PHP 8192:  Non-static method fittingTools::shipEffects() should not be called statically in /public/mods/ship_display_tool/init.php on line 407
PHP message: PHP 8192:  Non-static method fittingTools::setlevel5Skills() should not be called statically in /public/mods/ship_display_tool/init.php on line 408
PHP message: PHP 8192:  Non-static method fittingTools::getExtraStats() should not be called statically in /public/mods/ship_display_tool/init.php on line 409
PHP message: PHP 8192:  Non-static method fittingTools::setAndOrderShipResists() should not be called statically in /public/mods/ship_display_tool/init.php on line 872
PHP message: PHP 8192:  Non-static method fittingTools::tankAbleDPS() should not be called statically in /public/mods/ship_display_tool/init.php on line 889
PHP message: PHP 8192:  Non-static method fittingTools::peakShieldRecharge() should not be called statically in /public/mods/ship_display_tool/init.php on line 889
PHP message: PHP 8192:  Non-static method fittingTools::effectHP() should not be called statically in /public/mods/ship_display_tool/init.php on line 894
PHP message: PHP 8192:  Non-static method fittingTools::effectHP() should not be called statically in /public/mods/ship_display_tool/init.php on line 895
PHP message: PHP 8192:  Non-static method fittingTools::effectHP() should not be called statically in /public/mods/ship_display_tool/init.php on line 896
PHP message: PHP 8192:  Non-static method fittingTools::peakShieldRecharge() should not be called statically in /public/mo`

**Comment by Salvoxia** [comment]
Hi,

your problems seem to be caused by an old version of the Ship Display Tool, not EDK itself. 
Please try the latest version of that mod: 
https://github.com/Salvoxia/ship_display_tool/releases/latest

Best Regards,
Salvoxia

**Comment by sn0opy** [comment]
Oh, didn't even know that this wasn't the default. thanks, will have a look at it!
