### ISSUE TITLE
unable to edit EDK site

### ISSUE THREAD

**Issue by CokkocZateki** [evekb/evedev-kb#62]
Hi

Ive had this issue for a while now and wanted to see if anyone has a solution on this. Basically you cannot edit anything on the site. any settings changed will revert to the setting before after clicking save.

the only error that pops up is 

PHP 2016-06-12 09:06:44 2:  include(/var/www/killboard/evedev-kb-R4.2.22.0/common/smarty/plugins/modifier.date_format.php): failed to open stream: No such file or directory in /var/www/killboard/cache/templates_c/default/75fe17ee4fe2548179f51e50f3516b4944332e0b.file.killlisttable.tpl.php on line 20
PHP 2016-06-12 09:06:44 2:  include(): Failed opening '/var/www/killboard/evedev-kb-R4.2.22.0/common/smarty/plugins/modifier.date_format.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear::./common/includes') in /var/www/killboard/cache/templates_c/default/75fe17ee4fe2548179f51e50f3516b4944332e0b.file.killlisttable.tpl.php on line 20

could this be the cause of the site not updating?

**Comment by Salvoxia** [comment]
Hi,

has this every worked properly? If so, what did change? 
Are these errors directly related to failed edit tries?

Best Regards,
Salvoxia

**Comment by CokkocZateki** [comment]
hi @Salvoxia 

nope it has never worked properly on this server. on my corp own site it works seamlessly. But for some reason this just doesnt want to work

**Comment by CokkocZateki** [comment]
@Salvoxia do u have a email that i can pm you on regarding this issue please

**Comment by Salvoxia** [comment]
@CokkocZateki sure, you can reach me at salvoxia@blindfish.info
