### ISSUE TITLE
zkb import misses kills

### ISSUE THREAD

**Issue by ghost** [evekb/evedev-kb#64]
Hey,

So I've found an issue with the zkb import that I will try to explain below:

If zkb import runs at time X, it pulls all kills up to time X.  Now someone posts a killmail that occured 30 minutes before X (like if the cron runs during a fleet fight).  The zkb import runs again, but it only looks at kills that were from after time X, so it misses the posted killmail.

This is a problem during fleet fights, since a killmail may be posted immediately, the cron runs, then all the killmails before the last one are skipped.  I recommend the zkb importer always looks at killmails within the last X-4 hours time or something like that instead of just at X itself.

Obviously it will miss super old killmails, but this would go much further in fixing the current missing ones.

**Comment by Salvoxia** [comment]
Hi,

actually, the behavior you suggest already exists. The setting for it is called "Negative last kill timestamp offset [h]" in the zKBFetch settings. This is the number of hours to subtract from the timestamp of the last fetched kill. Set it to 4 to achieve the proposed 4 hour offset.

Best Regards,
Salvoxia

**Comment by ghost** [comment]
You're right!  Thanks
