### ISSUE TITLE
step 4 error

### ISSUE THREAD

**Issue by MMGIFL** [evekb/evedev-kb#65]
Fatal error: Uncaught Error: Call to a member function fetch_array() on boolean in /var/www/html/killboard/install/install_step4.php:278 Stack trace: #0 /var/www/html/killboard/install/index.php(80): include() #1 {main} thrown in /var/www/html/killboard/install/install_step4.php on line 278

what am I doing wrong?

**Comment by MMGIFL** [comment]
Creating table kb3_apilog...Error: Invalid default value for 'log_timestamp'
Creating table kb3_comments...Error: Invalid default value for 'posttime'
Creating table kb3_contracts...Error: Invalid default value for 'ctr_started'
Creating table kb3_inv_detail...Error: Invalid default value for 'ind_timestamp'
Creating table kb3_kills...Error: Invalid default value for 'kll_timestamp'
Creating table kb3_log...Error: Invalid default value for 'log_timestamp'
Creating table kb3_mails...Error: Invalid default value for 'kll_timestamp'

is also listed at the top of the page

**Comment by Salvoxia** [comment]
Hi,

my first guess is that your MySQL server is running in [NO_ZERO_DATE](http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date) mode. Could you try turning that off, wipe your database clean, clear your browser's cookies (so that installation starts from the beginning) and try again?

Best Regards,
Salvoxia

**Comment by MMGIFL** [comment]
@Salvoxia after looking into the closed issues I think the issue might actually be im running php7?

**Comment by Salvoxia** [comment]
Hi,

I doubt that, EDK has been made PHP7 compliant some time ago. The errors you're getting show that the core database tables could not be created. The default values set for timestamp columns in these tables would cause this error in NO_ZERO_DATE mode.

Best Regards,
Salvoxia

**Comment by MMGIFL** [comment]
@Salvoxia okay I will turn off strict mode and try again

**Comment by MMGIFL** [comment]
@Salvoxia that worked thank you.
