### ISSUE TITLE
Kills with only citadels as the killer do not properly pull

### ISSUE THREAD

**Issue by ghost** [evekb/evedev-kb#66]
An example kill is: https://crest-tq.eveonline.com/killmails/56071090/7cc4493ff1a76e327217b36c5457bb335c84f647/ (https://zkillboard.com/kill/56071090/)

If manually posted, it works.  However, API pulls, zkb kills, etc do not automatically pull them.

**Comment by Salvoxia** [comment]
Hi,

thanks for reporting!
I could recreate it with "ignore NPC only kills" checked, so it seems EDK classifies citadels as NPCs. Since citadels do not shoot by themselves, they shouldn't be classified as NPC. I will look into that.

Best Regards,
Salvoxia
