### ISSUE TITLE
PHP7 Support

### ISSUE THREAD

**Issue by ghost** [evekb/evedev-kb#68]
It'd be nice if this project was updated to be compatible with PHP7.  For example, its still using the extremely outdated mysql_query functions that were removed in PHP7.

The latest version of Ubuntu doesn't even have PHP5 in its repositories anymore.  PHP5 is EOL as of December 31 of this year (security updates ending in 2018).  For this project to survive, it needs to be updated to work on PHP7

**Comment by Salvoxia** [comment]
Hi,

EDK has been overhauled in January to be compatible with PHP7, and has been successfully installed on a PHP 7 system (for example, see the [commits for R4.2.19.0](https://github.com/evekb/evedev-kb/commit/7f856cbccfead1065a0d9831fc42f385856d911a), which took care of most the incompatible stuff).
I still found four occurrences of mysql_query, this will be fixed. Did you run in any other problems while using PHP7?

Best Regards,
Salvoxia
