### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by thomaslener** [evekb/evedev-kb#69]
Moving to new Server, got this error:

Database error: Expression #1 of ORDER BY clause is not in SELECT list, references column 'killboard_.inc.inc_timestamp' which is not in SELECT list; this is incompatible with DISTINCT
SQL: SELECT DISTINCT kll_id FROM kb3_kills kll STRAIGHT_JOIN kb3_ships shp ON ( shp.shp_id = kll.kll_ship_id ) STRAIGHT_JOIN kb3_ship_classes scl ON ( scl.scl_id = shp.shp_class ) INNER JOIN kb3_inv_crp inc ON (inc.inc_kll_id = kll.kll_id) WHERE inc.inc_crp_id in (1 ) AND inc.inc_timestamp >= '2016-11-14 00:00:00' AND inc.inc_timestamp <= '2016-11-20 23:59:59' AND shp.shp_class not in ( 2,3,11 ) order by inc.inc_timestamp desc

MySQL Version 5.7.16	
Tried with PHP Version 5.6.28 and 7.0.8

**Comment by Salvoxia** [comment]
Hi,

this is caused by changes in MySQL 5.7.5.
Please refer to to issue #67 for a fix.

Best Regards,
Salvoxia

**Comment by thomaslener** [comment]
Thanks, it works.
