### ISSUE TITLE
zkb api pull broken

### ISSUE THREAD

**Issue by ghost** [evekb/evedev-kb#70]
It looks like the zkb pulling is no longer working.  when I run it:

![img](https://vgy.me/zYCl3r.png)

![img](https://vgy.me/fxHIH9.png)

When I run the fetch via the web interface, 48 hours is removed from the "last kill timestamp fetch".  See below now (after running once from the previous screenshot):

![img](https://vgy.me/lxaZtG.png)

Now if you manually look at the link it says its pulling from, you can see the latest kill is actually today:

![img](https://vgy.me/VMJn2o.png)

Any ideas?  I can supply more info if you have questions

**Comment by ghost** [comment]
Unchecking "Ignore NPC only deaths" does not change anything.  Same problem exists with it unchecked

**Comment by Salvoxia** [comment]
Hi,

that's caused by changes to the zKB API. A fix is already available for EDK, but at the moment it won't help much, becasue zKB has been put into reinforeced mode (due to the M-O battle) and the API is not working at the moment.
A quick workaround can be found here: http://www.evekb.org/forum/viewtopic.php?f=503&p=49940#p49935
I'll push a more extensible fix as soon the zKB API is back up and I could test the fix.

Best Regards,
Salvoxia

**Comment by drkthunder02** [comment]
Any update on this change?

**Comment by Salvoxia** [comment]
Hi, 
a hotfix is available by using replacing your common/includes/class.zkbfetch.php with this one: 
https://raw.githubusercontent.com/evekb/evedev-kb/ddf7661ed0b5655e9d20369180722dfab3230277/common/includes/class.zkbfetch.php

Best Regards,
Salvoxia

**Comment by gourounios** [comment]
it seems that after the recent update my killboard wont fetch from zkill
any help would be appreciated

 
Administration - zKillboard Fetch v1.1
ZKBApi: https://zkillboard.com/api/combined/corporationID/1934706985/
0 kills were posted and 0 were skipped (1 kills fetched). Timestamp of last kill: 2017-01-10 08:00:00
Invalid format for kill, skipping
ZKBApi: https://zkillboard.com/api/combined/corporationID/99004227/
0 kills were posted and 0 were skipped (1 kills fetched). Timestamp of last kill: 2016-01-10 18:00:00
Invalid format for kill, skipping

**Comment by Salvoxia** [comment]
Hi,

please remove the "combined" modifier from your fetch URLs. 
Is was only present in one specific branch of zKB and never really made it to zKillboard.com, but until recently the zKB API did not bother whether it was there or not.
Now it seems it only accepts known modifiers (which is completely understandable).

Please try using these URLS:
```
https://zkillboard.com/api/corporationID/1934706985/
```
```
https://zkillboard.com/api/corporationID/99004227/
```

The example URLs in the zKB Fetch configuration should have been updated some time ago to no longer show the combined modifier.

Best Regards,
Salvoxia
