### ISSUE TITLE
Error: the xajax Javascript component could not be included. Perhaps the URL is incorrect?

### ISSUE THREAD

**Issue by KongGal** [evekb/evedev-kb#77]
```
Error: the xajax Javascript component could not be included. Perhaps the URL is incorrect?
URL: http://kb.tluc.me/common/xajax/xajax_js/xajax_core.js
```
I'm running the site on a SSL connection which seems to mess up the killboard due to not being able to load none HTTPS sites
What file would i have to edit to force it into https instead of http?
  
With that said i am running a Permanent SEO-safe 301 redirect from HTTP to HTTPS
But some where in the files its trying to access the files as HTTP instead of HTTPS which SSL don't like due to be unsecure sources / scripts

**Comment by Salvoxia** [comment]
Hi,

Make sure both the "Killboard Host" and "Image base URL" in ACP -> Configuration start with https://. That base URL is used to construct links and include style sheets/java script/local image files.

Best Regards,
Salvoxia

**Comment by KongGal** [comment]
I had all 3 set to https
main webpage link, killboard host and image base URL

but its like somewhere in the code it tries to load the xajax_core.js with just http which then screws it up due to HTTPS don't want to load http scripts

**Comment by Salvoxia** [comment]
When visiting your killboard and manually typing in "https://.." it won't event load the style sheet. 
This is the line adding the java script file to the page header: https://github.com/evekb/evedev-kb/blob/4.0/common/xajax/xajax.php#L41
It is constructed using the configured killboard host and a harcoded suffix.

Also, all links on your killboard link to http://.., so something must be wrong with that setting. Caching issue maybe?

**Comment by KongGal** [comment]
I changed it from https to http to make the KB work but let me just reenable it

**Comment by KongGal** [comment]
`https://kb.tluc.me/`

There you have the site running in SSL but due to xajax is trying to load via HTTP its getting blocked due to being unsecure script if you in chrome tell it to load unsecure scripts then it loads the site fine, you do that by clicking the little shield with a red box and you would have to do that every time

**Comment by KongGal** [comment]
If i login on the admin page it loads the site fine and no problems but if i log out then the issue is back

**Comment by Salvoxia** [comment]
Hmm, must definitely be a caching issue, AJAX works fine with me (on https). Checked on your search page. Could be some browser-side caching?

**Comment by Salvoxia** [comment]
Since this seems to be working, I'll close this issue.
