### ISSUE TITLE
Campaign display not working

### ISSUE THREAD

**Issue by CokkocZateki** [evekb/evedev-kb#81]
Hi.
For some reason our campaign display on the front page shows zero values yet we got loads of kills and losses. any idea how to fix it

![image](https://user-images.githubusercontent.com/16074209/26889175-8b93c944-4bad-11e7-926c-6ad5a63645b7.png)

**Comment by Salvoxia** [comment]
What target entities did you add to the campaign?

**Comment by CokkocZateki** [comment]
i added the alliance name and region

**Comment by CokkocZateki** [comment]
ahhh i shouldnt have added the alliance name. noob lol

**Comment by CokkocZateki** [comment]
i close this
