### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by CokkocZateki** [evekb/evedev-kb#83]
Hi
on step 4 i suddenly hit a speedbump

![image](https://user-images.githubusercontent.com/16074209/29267615-b21031c2-80e9-11e7-886a-48b722d46d3b.png)

any workarounds of fixed.

thanks

**Comment by Salvoxia** [comment]
Hi,

did you use the latest KB release (4.2.33.0) or the latest dev version from the 4.0-dev branch?
Also, what MySQL version are you using?

Best Regards,
Salvoxia

**Comment by CokkocZateki** [comment]
hi @Salvoxia 

im using KB releaase 4.2.33.0 and MySQL version 5.7.19

**Comment by Salvoxia** [comment]
Hi,

this might be related to #82.
Could you please replace your packages folder with the one from the 4.0-dev branch and try again?

Best Regards,
Salvoxia

**Comment by CokkocZateki** [comment]
how would i do that sorry

**Comment by Salvoxia** [comment]
You can download the current dev version here: https://github.com/evekb/evedev-kb/archive/4.0-dev.zip

**Comment by CokkocZateki** [comment]
get the below after i downloaded the dev version

```
Database error: Expression #1 of ORDER BY clause is not in SELECT list, references column 'killboard.ina.ina_timestamp' which is not in SELECT list; this is incompatible with DISTINCT
SQL: SELECT DISTINCT kll_id FROM kb3_kills kll STRAIGHT_JOIN kb3_ships shp ON ( shp.shp_id = kll.kll_ship_id ) STRAIGHT_JOIN kb3_ship_classes scl ON ( scl.scl_id = shp.shp_class ) INNER JOIN kb3_inv_all ina ON (ina.ina_kll_id = kll.kll_id) WHERE ina.ina_all_id in (1 ) AND ina.ina_timestamp >= '2017-08-14 00:00:00' AND ina.ina_timestamp <= '2017-08-20 23:59:59' AND shp.shp_class not in ( 2,3,11,53 ) order by ina.ina_timestamp desc
```

**Comment by Salvoxia** [comment]
Okay, that's a different issue, the first one seems resolved.

That MySQL version comes with a MySQL mode (ONLY_FULL_GROUP_BY) enabled by default, that is not compatible with EDK.
Please see here for how to disabling that mode: https://github.com/evekb/evedev-kb/issues/76#issuecomment-294426653

**Comment by CokkocZateki** [comment]
awesome.so the solution was to run `SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`
