### ISSUE TITLE
ESI api integration

### ISSUE THREAD

**Issue by jaightaylor** [evekb/evedev-kb#85]
CCP pulled the plug on CREST, so newly generated URL's aren't parsing at all. 

~~Currently the work around is to post to Zkill, then pull the CREST url from there.~~ NOPE.

**Comment by cvweiss** [comment]
zkill doesn't even provide the crest url anymore though

**Comment by Salvoxia** [comment]
Did I miss some sort of announcement about a CREST shutdown date?
Will look into this.

Edit: Seems like "only" the external link is now an ESI link, CREST still works

**Comment by Salvoxia** [comment]
Please see the mentioned commit for a hotfix.

**Comment by Salvoxia** [comment]
Or simply use [this](https://raw.githubusercontent.com/evekb/evedev-kb/fee72d8c9e2233142206cf7e26386f0176658286/common/includes/class.crestparser.php) modified CREST parser, or else you'd have to consider both the commits above, because I can't git.

**Comment by Salvoxia** [comment]
This is now live with R4.2.34.0
