### ISSUE TITLE
Fresh install of EDK 4.2.36.0

### ISSUE THREAD

**Issue by Rayvenhaus** [evekb/evedev-kb#86]
I've just rebuilt my server. Fresh install of LAMP (Ubuntu 16.04, Apache2, PHP 7 and MySQL Server 5.7). I am able to complete the installation steps and on the last page, where it says I can visit my new site (killboard), when I click on that link, I get the following displayed on a webpage:

```
Database error: Expression #1 of ORDER BY clause is not in SELECT list, references column 'alliance_killboard.inc.inc_timestamp' which is not in SELECT list; this is incompatible with DISTINCT
SQL: SELECT DISTINCT kll_id FROM kb3_kills kll STRAIGHT_JOIN kb3_ships shp ON ( shp.shp_id = kll.kll_ship_id ) STRAIGHT_JOIN kb3_ship_classes scl ON ( scl.scl_id = shp.shp_class ) INNER JOIN kb3_inv_crp inc ON (inc.inc_kll_id = kll.kll_id) WHERE inc.inc_crp_id in (1 ) AND inc.inc_timestamp >= '2018-01-08 00:00:00' AND inc.inc_timestamp <= '2018-01-14 23:59:59' AND shp.shp_class not in ( 2,3,11,53 ) order by inc.inc_timestamp desc
```

I am unable to run the killboard as this is all it displays

**Comment by Rayvenhaus** [comment]
Here is the fix:

Add this:

[mysqld]
sql-mode=""

To:
/etc/mysql/my.cnf

Mysql 5.7 on Ubuntu 16.04

**Comment by Salvoxia** [comment]
The requirement to have ONLY_FULL_GROUP_BY turned off is now included in the installation requirements displayed during the installation process: 
https://github.com/evekb/evedev-kb/blob/4.4-dev/install/templates/install_step1.tpl#L5
