### ISSUE TITLE
Esi removing /corporation/names, /alliances/names on 21.6

### ISSUE THREAD

**Issue by Fundaris** [evekb/evedev-kb#89]
As I noticed last time that u are using them.

https://twitter.com/TeamTechCo/status/1008796939394174976

Kind Regards

Edit: universe/names support up to 1k :)

**Comment by Salvoxia** [comment]
Thank you for the heads up, I switched to /universe/names for characters, corporations and alliances since the removal of /characters/names and /corporations/names :)
See https://github.com/evekb/evedev-kb/commit/12431ca96e790eae2692601a25bdea85eb668dad
